services:
  back:
    image: adriendavy/hopingo-back
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true

    env_file:
      - database.env
      - backend.env
    healthcheck:
      test: 'curl --fail  --request POST --header ''Content-Type: application/json'' --url ''http://localhost:5000/'' --data ''{"query": "query { __typename }"}'''
      interval: 5s
      timeout: 260s

  front:
    image: adriendavy/hopingo-front
    entrypoint: sh
    command: -c "npx vite --host"
    environment:
      - GRAPHQL_SCHEMA_URL=http://back:5000
    ports:
      - 5173:5173 # host_port:container_port

    depends_on:
      back:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 8080:80
    depends_on:
      - back
      - front

volumes:
  dbdata:
    driver: local
