name: vitest-and-docker-ci

on: push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Goto client and run tests
        run: cd frontend && npm i && npm test
  docker-front:
    needs: test-front
    if: github.ref == 'refs/heads/${{ github.event.repository.default_branch }}'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:frontend"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hopingo-front:latest
  test-back:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Goto server and run tests
        run: cd backend && npm i && npm run test:postgres
  docker-back:
    needs: test-back
    if: github.ref == 'refs/heads/${{ github.event.repository.default_branch }}'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:backend"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hopingo-back:latest
